/**
 * Sample Jobs Data
 * 
 * Use this to seed your Firebase database with sample jobs
 * You can run this or manually add jobs via the /api/jobs POST endpoint
 */

export const SAMPLE_JOBS = [
    {
        id: 'job-1',
        title: 'Senior React Developer',
        company: 'Tech Company A',
        description:
            'Looking for an experienced React developer to build scalable web applications. Must have 5+ years of experience with React and TypeScript.',
        salary: 150000,
        location: 'USA',
        jobType: 'Full-time',
        workLocation: 'digital',
        skills: ['React', 'TypeScript', 'Next.js', 'Node.js'],
        postedDate: new Date().toISOString(),
        url: 'https://example.com/jobs/1',
    },
    {
        id: 'job-2',
        title: 'Full Stack Developer',
        company: 'Remote Startup',
        description:
            'Join our fast-growing startup as a Full Stack Developer. Work with modern tech stack including Next.js, PostgreSQL, and Docker.',
        salary: 120000,
        location: 'Remote',
        jobType: 'Full-time',
        workLocation: 'digital',
        skills: ['Next.js', 'Python', 'PostgreSQL', 'Docker'],
        postedDate: new Date().toISOString(),
        url: 'https://example.com/jobs/2',
    },
    {
        id: 'job-3',
        title: 'DevOps Engineer',
        company: 'Cloud Solutions Inc',
        description:
            'Experienced DevOps Engineer needed to manage AWS infrastructure and CI/CD pipelines. Strong Kubernetes and Docker experience required.',
        salary: 140000,
        location: 'Europe',
        jobType: 'Full-time',
        workLocation: 'hybrid',
        skills: ['Kubernetes', 'Docker', 'AWS', 'Terraform'],
        postedDate: new Date().toISOString(),
        url: 'https://example.com/jobs/3',
    },
    {
        id: 'job-4',
        title: 'Vue.js Developer',
        company: 'Web Agency',
        description: 'Frontend developer needed for Vue.js projects. Experience with Nuxt.js and Tailwind CSS is a plus.',
        salary: 90000,
        location: 'India',
        jobType: 'Full-time',
        workLocation: 'digital',
        skills: ['Vue', 'Nuxt.js', 'Tailwind CSS', 'JavaScript'],
        postedDate: new Date().toISOString(),
        url: 'https://example.com/jobs/4',
    },
    {
        id: 'job-5',
        title: 'Python Backend Developer',
        company: 'Data Analytics Firm',
        description:
            'Backend developer experienced with FastAPI and Django. Familiar with data processing and APIs. Salary range: $100k-$130k',
        salary: 115000,
        location: 'USA',
        jobType: 'Full-time',
        workLocation: 'onsite',
        skills: ['Python', 'FastAPI', 'PostgreSQL', 'Redis'],
        postedDate: new Date().toISOString(),
        url: 'https://example.com/jobs/5',
    },
    {
        id: 'job-6',
        title: 'Go Developer (Contract)',
        company: 'Blockchain Startup',
        description: 'Short-term contract position for Go developer. Building high-performance backend systems. 3-6 month engagement.',
        salary: 80000,
        location: 'Remote',
        jobType: 'Contract',
        workLocation: 'digital',
        skills: ['Go', 'Rust', 'Blockchain', 'gRPC'],
        postedDate: new Date().toISOString(),
        url: 'https://example.com/jobs/6',
    },
    {
        id: 'job-7',
        title: 'Rust Systems Engineer',
        company: 'Systems Software Co',
        description:
            'Looking for Rust expert to build high-performance systems. Experience with concurrency and performance optimization required.',
        salary: 160000,
        location: 'USA',
        jobType: 'Full-time',
        workLocation: 'hybrid',
        skills: ['Rust', 'C++', 'Systems Design', 'Performance'],
        postedDate: new Date().toISOString(),
        url: 'https://example.com/jobs/7',
    },
    {
        id: 'job-8',
        title: 'Angular Developer',
        company: 'Enterprise Software',
        description: 'Enterprise applications developer. 5+ years Angular experience. Must have RxJS and TypeScript expertise.',
        salary: 130000,
        location: 'UK',
        jobType: 'Full-time',
        workLocation: 'onsite',
        skills: ['Angular', 'TypeScript', 'RxJS', 'Node.js'],
        postedDate: new Date().toISOString(),
        url: 'https://example.com/jobs/8',
    },
    {
        id: 'job-9',
        title: 'Junior Developer Internship',
        company: 'Tech Academy',
        description:
            'Internship program for junior developers. Learn modern web development with mentorship from experienced developers.',
        salary: 25000,
        location: 'Canada',
        jobType: 'Internship',
        workLocation: 'hybrid',
        skills: ['React', 'Node.js', 'JavaScript', 'HTML/CSS'],
        postedDate: new Date().toISOString(),
        url: 'https://example.com/jobs/9',
    },
    {
        id: 'job-10',
        title: 'Freelance WordPress Developer',
        company: 'Digital Agency',
        description: 'Looking for WordPress specialist for ongoing freelance projects. PHP customization experience required.',
        salary: 50000,
        location: 'Remote',
        jobType: 'Freelance',
        workLocation: 'digital',
        skills: ['WordPress', 'PHP', 'JavaScript', 'MySQL'],
        postedDate: new Date().toISOString(),
        url: 'https://example.com/jobs/10',
    },
];
